### ISSUE TITLE
Decompiled the API

### ISSUE THREAD

**Issue by BebopKerman** [Anatid/XML-Documentation-for-the-KSP-API#18]
After a while, I figured out that this git repo didn't have all the classes in KSP. After enough copy-pasting of files from Visual Studio, I threw up my hands decompiled Assembly-CSharp.dll and Assembly-Charp-firstpass.dll. But daaaaang...

I found 1615 .cs files!! There's no way you can navigate that in the flat class list any more. Thankfully, they seem to live in well-organized namespaces.

Is there a reason why we don't have this giant list of files in this github right now? Is there some license restriction? Would I get in trouble with Squad if I pushed the source (as well as the function calls) to Github? What do you want me to do with them?

**Comment by Anatid** [comment]
Publishing the decompiled source is against the EULA. Understandably, Squad doesn't want the source code for their game made public.

**Comment by BebopKerman** [comment]
Yeah, I figured as much. I would still like to know where the line is, because I think some of these functions could he very powerful.

As there are no header files in C#, what counts as source and what as interface? Are there functions that are off limits to call?

**Comment by Anatid** [comment]
It's fine to publish anything you can see through the Object Browser. Basically that means method signatures for public functions.

**Comment by BebopKerman** [comment]
Alright, that's my goal. The Object Browser was just slow, so I exported them with another tool.

I'll have to look through them carefully to make sure they don't have any actual code. Would you accept 1600 header files? 

(Right now, it's big enough that Doxygen crashes before finishing. Deterministicly too, strangely enough. I think some Doxyfile hax might be needed to do it in pieces, but that makes my little project way more complicated than just a little Unix-fu.)

**Comment by Anatid** [comment]
I don't want to include plain "header files" in this project. That has no advantage over the Object Browser. This project is for collecting comments people have written about how to use the public methods in the API. If I include all the hundreds of other classes people haven't written anything about, they'll overwhelm the actual documentation.

**Comment by BebopKerman** [comment]
Ah, I didn't think of that.

Maybe we should make note of the fact that this documentation does NOT
contain all the classes? I for one thought for way too long that the
classes documented here were the only ones that exist.

I think a separate page that lists all namespaces and what's generally in
them would help.

I don't want to include plain "header files" in this project. That has no
advantage over the Object Browser. This project is for collecting comments
people have written about how to use the public methods in the API. If I
include all the hundreds of other classes people haven't written anything
about, they'll overwhelm the actual documentation.

—
Reply to this email directly or view it on GitHub
<https://github.com/Anatid/XML-Documentation-for-the-KSP-API/issues/18#issuecomment-113913047>
.
